/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_jswin_CallProc */

#ifndef _Included_com_googlecode_jswin_CallProc
#define _Included_com_googlecode_jswin_CallProc
#ifdef __cplusplus
extern "C" {
#endif
#undef com_googlecode_jswin_CallProc_CALLBACK_SIZE
#define com_googlecode_jswin_CallProc_CALLBACK_SIZE 32L

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    initCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_initCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    newRef
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_jswin_CallProc_newRef
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    delRef
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_delRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    memcpy
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_memcpy
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    strlen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_jswin_CallProc_strlen
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    getMem1
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_com_googlecode_jswin_CallProc_getMem1
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    getMem2
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_com_googlecode_jswin_CallProc_getMem2
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    getMem4
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_jswin_CallProc_getMem4
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    getByteArray
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_getByteArray
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    getShortArray
 * Signature: (I[SII)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_getShortArray
  (JNIEnv *, jclass, jint, jshortArray, jint, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    getIntArray
 * Signature: (I[III)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_getIntArray
  (JNIEnv *, jclass, jint, jintArray, jint, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    putMem1
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_putMem1
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    putMem2
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_putMem2
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    putMem4
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_putMem4
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    putByteArray
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_putByteArray
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    putShortArray
 * Signature: (I[SII)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_putShortArray
  (JNIEnv *, jclass, jint, jshortArray, jint, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    putIntArray
 * Signature: (I[III)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_putIntArray
  (JNIEnv *, jclass, jint, jintArray, jint, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    alloc
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_jswin_CallProc_alloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_free
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    loadLibrary
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_jswin_CallProc_loadLibrary
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    freeLibrary
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_freeLibrary
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    getProcAddress
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_jswin_CallProc_getProcAddress
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    callProc
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_jswin_CallProc_callProc
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_googlecode_jswin_CallProc
 * Method:    prepareCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_jswin_CallProc_prepareCallback
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
